---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: popcornail-blue
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/kinoite-main
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    repos:
      - https://raw.githubusercontent.com/MkKvcs/fedora/main/nordvpn.repo
    install:
        - chromium
        - zsh
        - neovim
        - easyeffects
        - nordvpn
        - fastfetch
    remove:

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    user:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      install:
        - com.obsproject.Studio
        - cafe.avery.Delfin
        - com.nordpass.NordPass
        - com.spotify.Client
        - com.discordapp.Discord
        - org.signal.Signal
        - org.qbittorrent.qBittorrent
        - com.stremio.Stremio
        - org.videolan.VLC
        - org.fedoraproject.MediaWriter
        - org.onlyoffice.desktopeditors
        - com.sindresorhus.Caprine

  - type: justfiles
    validate: false
    include:
      - overclock-display.just
    
  - type: script
    scripts:
      - chromium.sh

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

